import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateUnit, createInitialState, calculateGeometry, evaluateMeasurements, preliminaryScreening, STATUS, evaluateFRFUpdate } from '../src/worker-engine.js';

function qualifiedState() {
 const s=createInitialState(); s.unit.unitModel='MR-900'; const c=s.circuits[0]; c.geometryRevision='G1'; c.route=[{length:1000,unit:'mm',direction:'+X'}]; c.brazes=[{id:'first',distanceMM:300},{id:'final',distanceMM:800}]; c.operating={rpm:3000,pressure:250,temperatureC:50,measuredDominantHz:50};
 s.recipes=[{approved:true, empiricallyQualified:true, level:'empirical', unitModel:'MR-900',circuitId:'circuit-1',geometryRevision:'G1',revision:'R1',massG:130,location:{distanceMM:500,reference:'compressor outlet'},absoluteLimitMMs:6,qualifiedEnvelope:{rpm:{min:2900,max:3100},pressure:{min:200,max:300},temperatureC:{min:20,max:70}},comparisonTolerances:{rpm:50,pressure:10,temperatureC:2}}]; return s;
}
test('A known failed braze trial returns FAIL and retains signed reductions',()=>{const s=qualifiedState(),c=s.circuits[0]; const rows=[['first','vertical',9,6.76],['first','horizontal',16,22],['final','vertical',6,5.96],['final','horizontal',14,14.48]]; for(const [pointId,axis,b,a] of rows){c.testRecords.push({role:'support-baseline',pointId,axis,velocityMMs:b,unitModel:'MR-900',circuitId:'circuit-1',operatingCondition:'steady',rpm:3000,pressure:250,temperatureC:50,instrument:'I',velocityUnit:'mm/s'});c.testRecords.push({role:'post-installation',pointId,axis,velocityMMs:a,unitModel:'MR-900',circuitId:'circuit-1',operatingCondition:'steady',rpm:3000,pressure:250,temperatureC:50,instrument:'I',velocityUnit:'mm/s'});} const r=calculateUnit(s).results[0];assert.equal(r.status,STATUS.FAIL);assert.equal(r.measurement.rows[0].reductionPercent.toFixed(2),'24.89');assert.equal(r.measurement.rows[1].reductionPercent.toFixed(2),'-37.50');});
test('B unsupported 1860mm example cannot recommend a safe mass',()=>{const s=createInitialState();s.unit.unitModel='MR';const c=s.circuits[0];c.geometryRevision='G';c.route=[{length:1860,unit:'mm',direction:'+X'}];c.operating={rpm:3000,measuredNaturalHz:35};const r=calculateUnit(s).results[0];assert.equal(r.status,STATUS.NOT_QUALIFIED);assert.match(r.workerInstruction,/Do not install/);assert.equal(preliminaryScreening(c).status,STATUS.SCREENING_ONLY);});
test('C measured dominant frequency is retained by screening',()=>{const c={operating:{rpm:3000,measuredDominantHz:42}};assert.equal(preliminaryScreening(c).measuredDominantHz,42);c.operating.measuredDominantHz=61;assert.equal(preliminaryScreening(c).measuredDominantHz,61);});
test('D zero-mass valid recipe is not replaced',()=>{const s=qualifiedState();s.recipes[0].massG=0;const c=s.circuits[0];for(const [p,a] of [['first','vertical'],['final','horizontal']]){for(const [role,v] of [['support-baseline',10],['post-installation',4]])c.testRecords.push({role,pointId:p,axis:a,velocityMMs:v,unitModel:'MR-900',circuitId:'circuit-1',operatingCondition:'steady',rpm:3000,pressure:250,temperatureC:50,instrument:'I',velocityUnit:'mm/s'});}assert.match(calculateUnit(s).results[0].workerInstruction,/0 g/);});
test('E complex FRF requires phase and quality',()=>{assert.equal(evaluateFRFUpdate({frequencies:[10],real:[1],imag:[0],massKg:.1,dof:0,coherence:[.95]}).valid,true);assert.equal(evaluateFRFUpdate({frequencies:[10],real:[1],imag:[0],massKg:.1,dof:0,coherence:[.2]}).valid,false);});
test('H canonical 3D route handles horizontal vertical diagonal and U shape',()=>{const g=calculateGeometry([{length:100,unit:'mm',direction:'+X'},{length:50,unit:'mm',direction:'+Y'},{length:100,unit:'mm',direction:'-X'}]);assert.equal(g.distanceMM,250);assert.deepEqual(g.end,[0,50,0]);});
test('I P00 serial is migrated separately',()=>{const s=createInitialState();s.unit.unitModel='P001';const out=calculateUnit(s);assert.equal(out.state.unit.serialNumber,'P001');assert.equal(out.state.unit.unitModel,'');});
test('J incompatible readings warn and cannot pass',()=>{const m=evaluateMeasurements({baseline:[{pointId:'b',axis:'vertical',velocityMMs:10,rpm:3000}],after:[{pointId:'b',axis:'vertical',velocityMMs:1,rpm:3300}] ,tolerances:{rpm:10}});assert.equal(m.pass,false);});
