import { createInitialState, calculateUnit } from './worker-engine.js';
import { signIn, signOut, observeAuth, profile, approvedRecipes, saveTestRecord, legacyModels } from './firebase-client.js';

const $ = id => document.getElementById(id);
let userProfile = null, recipes = [], legacy = [], state = null;
const err = e => e?.message || 'Unable to complete that action.';
function selectedRecipe() { return recipes.find(r => r.unitModel === $('model').value.trim() && r.circuitId === $('circuit').value); }
function refreshCircuits() { const model = $('model').value.trim(); const values = [...new Set(recipes.filter(r => r.unitModel === model).map(r => r.circuitId))]; $('circuit').innerHTML = values.length ? values.map(v => `<option value="${v}">${v}</option>`).join('') : '<option value="circuit-1">Circuit 1</option>'; }
function renderLegacyModels() { const select = $('savedModels'); if (!select) return; select.innerHTML = '<option value="">Select saved model</option>' + legacy.map(r => `<option value="${r.model || r.id}">${r.model || r.id}</option>`).join(''); }
function render() { const r = calculateUnit(state).results[0]; $('result').innerHTML = `<article class="${r.status === 'PASS' ? 'PASS' : r.status === 'FAIL' ? 'FAIL' : 'NOT'} card"><h3>${r.status}</h3><p>${r.workerInstruction}</p><small>${r.reasons.join(' ')}</small></article>`; return r; }
function prepare() { const recipe = selectedRecipe(); state = createInitialState(); state.unit.unitModel = $('model').value.trim(); state.recipes = recipes; const c = state.circuits[0]; c.id = $('circuit').value; c.geometryRevision = recipe?.geometryRevision || ''; c.operating = { rpm: +$('rpm').value, pressure: +$('pressure').value, pressureUnit: 'psi' }; c.testRecords = $('base').value ? [{ role: 'support-baseline', pointId: 'first-braze', axis: 'vertical', velocityMMs: +$('base').value, unitModel: state.unit.unitModel, circuitId: c.id, operatingCondition: 'steady', rpm: +$('rpm').value, pressure: +$('pressure').value, velocityUnit: 'mm/s' }] : []; }

$('login').onclick = async () => { try { $('loginMessage').textContent = 'Signing in…'; await signIn($('email').value, $('password').value); $('loginMessage').textContent = ''; } catch (e) { $('loginMessage').textContent = err(e); } };
$('logout').onclick = () => signOut();
$('model').addEventListener('input', refreshCircuits);
$('savedModels').onchange = e => { if (e.target.value) { $('model').value = e.target.value; refreshCircuits(); } };
$('run').onclick = () => { prepare(); $('installation').hidden = false; render(); };
$('verify').onclick = async () => { if (!state) prepare(); if ($('after').value) state.circuits[0].testRecords.push({ role: 'post-installation', pointId: 'first-braze', axis: 'vertical', velocityMMs: +$('after').value, unitModel: state.unit.unitModel, circuitId: state.circuits[0].id, operatingCondition: 'steady', rpm: +$('rpm').value, pressure: +$('pressure').value, velocityUnit: 'mm/s' }); const result = render(); try { await saveTestRecord({ scopeId: userProfile.scopes?.[0], submittedBy: userProfile.uid, unitModel: state.unit.unitModel, circuitId: state.circuits[0].id, status: result.status, measurement: result.measurement || null }); } catch (e) { $('result').insertAdjacentHTML('beforeend', `<p class="warn">Result was not saved: ${err(e)}</p>`); } };
observeAuth(async user => { if (!user) { userProfile = null; recipes = []; legacy = []; $('loginCard').classList.remove('hidden'); $('app').classList.add('hidden'); return; } try { userProfile = await profile(user.uid); recipes = await approvedRecipes(userProfile.scopes?.[0]); legacy = ['engineer','administrator'].includes(userProfile.role) ? await legacyModels() : []; $('identity').textContent = `Signed in as ${user.email} (${userProfile.role}).`; $('loginCard').classList.add('hidden'); $('app').classList.remove('hidden'); renderLegacyModels(); refreshCircuits(); } catch (e) { $('loginMessage').textContent = err(e); await signOut(); } }).catch(e => $('loginMessage').textContent = err(e));
